In [ ]:
import itertools
import concurrent.futures
import constants as Cs
import os
import json
import datetime
import pickle
import optuna
from constants import EXAMPLE_MAPPING
SEEDS = list(range(101, 115))
TEST_EVAL_EPS = 5
# lambda fit archving [FrozenTrial(number=80, state=<TrialState.COMPLETE: 1>, values=[118.11550385203829], datetime_start=datetime.datetime(2026, 5, 22, 5, 4, 53, 822616), datetime_complete=datetime.datetime(2026, 5, 22, 5, 36, 8, 359073), params={'crossmethod': 'uniform', 'lambda': 70, 'mu': 70, 'mutation_rate': 0.01, 'cross_rate': 0.9000000000000001, 'sigma': 0.5, 'archiving_period': 4, 'archive_batch': 5, 'cross': 0.6}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'crossmethod': CategoricalDistribution(choices=('uniform', 'mean')), 'lambda': CategoricalDistribution(choices=(40, 50, 60, 70)), 'mu': CategoricalDistribution(choices=(40, 50, 60, 70)), 'mutation_rate': FloatDistribution(high=0.1, log=False, low=0.0, step=0.01), 'cross_rate': FloatDistribution(high=1.0, log=False, low=0.3, step=0.1), 'sigma': FloatDistribution(high=3.0, log=False, low=0.5, step=0.5), 'archiving_period': IntDistribution(high=5, log=False, low=2, step=1), 'archive_batch': IntDistribution(high=5, log=False, low=1, step=1), 'cross': FloatDistribution(high=0.9, log=False, low=0.1, step=0.1)}, trial_id=81, value=None), FrozenTrial(number=86, state=<TrialState.COMPLETE: 1>, values=[118.11550385203829], datetime_start=datetime.datetime(2026, 5, 22, 5, 36, 31, 908497), datetime_complete=datetime.datetime(2026, 5, 22, 6, 11, 5, 128793), params={'crossmethod': 'uniform', 'lambda': 70, 'mu': 70, 'mutation_rate': 0.01, 'cross_rate': 0.9000000000000001, 'sigma': 0.5, 'archiving_period': 4, 'archive_batch': 5, 'cross': 0.6}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'crossmethod': CategoricalDistribution(choices=('uniform', 'mean')), 'lambda': CategoricalDistribution(choices=(40, 50, 60, 70)), 'mu': CategoricalDistribution(choices=(40, 50, 60, 70)), 'mutation_rate': FloatDistribution(high=0.1, log=False, low=0.0, step=0.01), 'cross_rate': FloatDistribution(high=1.0, log=False, low=0.3, step=0.1), 'sigma': FloatDistribution(high=3.0, log=False, low=0.5, step=0.5), 'archiving_period': IntDistribution(high=5, log=False, low=2, step=1), 'archive_batch': IntDistribution(high=5, log=False, low=1, step=1), 'cross': FloatDistribution(high=0.9, log=False, low=0.1, step=0.1)}, trial_id=87, value=None)]
# lambda - this one is bad actually novelty [FrozenTrial(number=4, state=<TrialState.COMPLETE: 1>, values=[-9.291787437438707], datetime_start=datetime.datetime(2026, 5, 19, 22, 25, 13, 886515), datetime_complete=datetime.datetime(2026, 5, 19, 23, 0, 16, 677521), params={'crossmethod': 'mean', 'lambda': 60, 'mu': 60, 'mutation_rate': 0.18, 'cross_rate': 1.0, 'sigma': 2.5}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'crossmethod': CategoricalDistribution(choices=('uniform', 'mean')), 'lambda': CategoricalDistribution(choices=(40, 50, 60, 70)), 'mu': CategoricalDistribution(choices=(40, 50, 60, 70)), 'mutation_rate': FloatDistribution(high=0.5, log=False, low=0.0, step=0.01), 'cross_rate': FloatDistribution(high=1.0, log=False, low=0.3, step=0.1), 'sigma': FloatDistribution(high=3.0, log=False, low=0.5, step=0.5)}, trial_id=208, value=None)]

GENS = {
    "cartpole": [25],
    "lunarlander":[50]
}
DECAYS = {
    "lunarlander":{
        "diff":[0.2, 0.5, 1.0, 1.5],
        "lambda":[0.5, 1.0, 2.0, 3.0]}
}

def rename(dict):
    return {EXAMPLE_MAPPING.get(k, k): v for k, v in dict.items()}

def task_job(en, alg, container, args, s, out_path):
    env = Cs.ENIVROMENTS[en]()
    df, pop = Cs.ALG_MAPPING[alg].argumented_function(env=en, container=container, seed=s, out_path=out_path, **args)
    print("Testing " + str(s))
    fitnesses = [env.evalutation_b(p, 42, TEST_EVAL_EPS) for p in pop]
    print("Finished seed %d of algorithm %s" % (s, alg))
    return fitnesses, pop


def evaluation_of_setup(en, alg, container, out_path, **kwargs):
    #we do not deviate the sigma
    # first we evaluate the current setup

    stat_futures = {}
    gens_future={}
    dec_future = {}
    args = rename(kwargs)
    dirpath = os.path.join(os.path.realpath(out_path), container,alg)

    with concurrent.futures.ProcessPoolExecutor(max_workers=5) as executor:
        print("Launching " + alg + "on Enviroment " + str(en))
        for dec, ng, s in itertools.product(DECAYS[en][alg], GENS[en], SEEDS):
            ags = args.copy()
            ags["ng"] = ng
            ags["decay"] = dec
            future = executor.submit(task_job, container=container, alg=alg, en=en, args=args, s=s, out_path=dirpath + "/stat")
            stat_futures[future] = s
            dec_future[future] = dec
            gens_future[future] = ng


    stats = {}
    pops = {}
    for future in concurrent.futures.as_completed(stat_futures):
        s = stat_futures[future]
        ng = gens_future[future]
        dec = dec_future[future]

        result = future.result()
        if "fitness" not in stats:
            stats["fitness"] = {}
        if dec not in stats["fitness"]:
            stats["fitness"][dec] = {}
        if ng not in stats["fitness"][dec]:  
            stats["fitness"][dec][ng] = {}

        stats["fitness"][dec][ng][s] = result[0]
        pops[s]= result[1] 
    ts = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{ts}_{container}_"+ "|".join(f"{k}: {v}" for k, v in args.items())
    stats["environment"] = en
    stats["algorithm"] = alg
    stats["container"] = container
    stats["arguments"] = args
    json_path = os.path.join(dirpath, filename + ".json")
    #pickle_path = os.path.join(dirpath, filename + ".plk")

    with open(json_path, "w") as json_file:
        json.dump(stats,json_file)
        print("Finished "+ filename)
    #with open(pickle_path, "wb") as f:
    #    pickle.dump(pops, f)
    return pops, stats

In [ ]:
import numpy as np

def select_minimal_exaples(examples):
    pop = np.inf
    selected_trials = []
    for t in examples:
        k = t["lambda"]+t["mu"]
        if pop == k:
            selected_trials.append(t)
        elif pop > k:
            pop = k
            selected_trials = [t]

    return selected_trials


def make_decay_examination(en, alg, container):
    with open("relevant_studies.json", "r") as f:
        relevant_study_names = json.load(f)
    storage = f"sqlite:///Data/optuna/{en}/{container}/{alg}.db"
    study_name = relevant_study_names[container][alg][en]

    new_study = optuna.load_study(study_name=study_name,storage=storage)
    most_promising = select_minimal_exaples([t.params for t in new_study.best_trials])
    pops, stats = evaluation_of_setup(
        en=en, 
        alg=alg, 
        container=container,
        out_path=f"./Data/decay_search/{en}",
        **most_promising[0]
    )
    return pops, stats

Launching lambdaon Enviroment lunarlander
   	      	                                fitness                                	                                novelty
   	      	-----------------------------------------------------------------------	------------------------------------------------------------------------
gen	nevals	avg     	gen	max     	min     	nevals	std    	avg     	gen	max     	min        	nevals	std
0  	70    	-383.202	0  	-125.803	-616.413	70    	144.004	0.401909	0  	0.800295	0.000330882	70    	0.223086
   	      	                                fitness                                	                                novelty
   	      	-----------------------------------------------------------------------	------------------------------------------------------------------------
gen	nevals	avg     	gen	max     	min     	nevals	std    	avg     	gen	max     	min      	nevals	std
0  	70    	-391.467	0  	-106.009	-718.135	70    	181.749	0.446759	0  	0.817091	0.0625404	70    	0.227439
   	      	                            fitness                            	                            novelty
   	      	---------------------------------------------------------------	----------------------------------------------------------------
gen	nevals	avg     	gen	max     	min    	nevals	std    	avg   	gen	max     	min      	nevals	std
0  	70    	-429.962	0  	-67.5599	-694.01	70    	188.832	0.3814	0  	0.810292	0.0154695	70    	0.209286
   	      	                            fitness                            	                                novelty
   	      	---------------------------------------------------------------	------------------------------------------------------------------------
gen	nevals	avg     	gen	max    	min     	nevals	std    	avg     	gen	max     	min       	nevals	std
0  	70    	-410.148	0  	2.20057	-731.976	70    	187.021	0.365898	0  	0.801468	0.00307456	70    	0.197449
   	      	                                fitness                                	                                novelty
   	      	-----------------------------------------------------------------------	------------------------------------------------------------------------
gen	nevals	avg     	gen	max     	min     	nevals	std    	avg     	gen	max     	min      	nevals	std
0  	70    	-475.161	0  	-58.9199	-800.383	70    	210.787	0.390347	0  	0.805722	0.0098418	70    	0.206634
1  	60    	-293.183	1  	-36.2659	-555.793	60    	136.065	0.504334	1  	0.801014	0.171323   	60    	0.20351
1  	60    	-284.612	1  	-129.649	-673.067	60    	139.13 	0.602181	1  	0.817091	0.31367  	60    	0.134781
1  	60    	-258.276	1  	2.20057	-572.615	60    	138.848	0.54738 	1  	0.801468	0.175233  	60    	0.148763
1  	60    	-283.204	1  	-52.1366	-682.89	60    	147.897	0.584815	1  	0.810292	0.274122 	60    	0.1357
1  	60    	-308.263	1  	-58.9199	-706.942	60    	185.213	0.560074	1  	0.818706	0.2      	60    	0.192565
2  	60    	-190.183	2  	-2.26426	-478.405	60    	106.522	0.629891	2  	0.802792	0.260795   	60    	0.15516
2  	60    	-166.811	2  	2.20057	-573.514	60    	110.446	0.65091 	2  	0.801652	0.260212  	60    	0.121163
2  	60    	-182.508	2  	-30.568 	-565.336	60    	86.2391	0.680902	2  	0.800593	0.296594 	60    	0.0905937
2  	60    	-174.959	2  	-38.3134	-420.136	60    	85.8956	0.681756	2  	0.810292	0.4265   	60    	0.10359
2  	60    	-175.264	2  	-58.9199	-585.308	60    	111.006	0.692584	2  	0.818706	0.305356 	60    	0.120958
3  	60    	-127.516	3  	-2.26426	-414.371	60    	58.327 	0.720907	3  	0.812871	0.252926   	60    	0.0968681
3  	60    	-108.32 	3  	2.20057	-369.276	60    	53.9317	0.722323	3  	0.805266	0.415114  	60    	0.0633546
3  	60    	-136.065	3  	-19.2016	-246.165	60    	52.244 	0.717105	3  	0.802676	0.540284 	60    	0.0558906
3  	60    	-132.008	3  	-58.9199	-340.715	60    	58.3057	0.746767	3  	0.818706	0.482255 	60    	0.0758553
3  	60    	-134.65 	3  	-2.0683 	-382.568	60    	69.0611	0.710069	3  	0.810292	0.33697  	60    	0.0921943
4  	60    	-102.244	4  	-2.26426	-278.941	60    	61.0326	0.759224	4  	0.812871	0.416546   	60    	0.0738375
4  	60    	-100.843	4  	-22.522	-258.641	60    	50.4348	0.73772 	4  	0.805266	0.534054  	60    	0.0491388
4  	60    	-113.85 	4  	-58.9199	-245.788	60    	30.6506	0.775942	4  	0.818706	0.609912 	60    	0.0421078
4  	60    	-111.371	4  	-22.5035	-246.165	60    	54.0541	0.743568	4  	0.800593	0.652217 	60    	0.0498363
4  	60    	-123.188	4  	-22.6534	-328.232	60    	56.9278	0.737313	4  	0.819785	0.396414 	60    	0.0820155
5  	60    	-93.2554	5  	0.326874	-170.437	60    	54.3168	0.780677	5  	0.812871	0.563638   	60    	0.0524172
5  	60    	-88.0318	5  	-22.522	-243.231	60    	35.4288	0.758429	5  	0.808927	0.655327  	60    	0.0341897
5  	60    	-78.0788	5  	-20.7797	-220.52 	60    	51.052 	0.761201	5  	0.800593	0.650343 	60    	0.0459587
5  	60    	-104.505	5  	-58.9199	-189.793	60    	21.2674	0.795594	5  	0.818706	0.650761 	60    	0.0290052
5  	60    	-104.855	5  	29.754  	-328.232	60    	54.5821	0.75472 	5  	0.819785	0.396414 	60    	0.0804423
6  	60    	-76.7166	6  	20.9548 	-146.742	60    	59.5442	0.78175 	6  	0.812871	0.570554   	60    	0.0563536
6  	60    	-78.1325	6  	-22.522	-243.231	60    	36.8454	0.765257	6  	0.808927	0.622824  	60    	0.0345731
6  	60    	-52.1667	6  	-20.1924	-193.426	60    	42.9003	0.777823	6  	0.806055	0.63481  	60    	0.0378271
6  	60    	-99.249 	6  	-21.6248	-137.043	60    	20.686 	0.798729	6  	0.818706	0.652634 	60    	0.0351972
6  	60    	-82.6634	6  	29.754  	-215.668	60    	49.7406	0.778458	6  	0.819785	0.526128 	60    	0.0560846
7  	60    	-62.3283	7  	20.9548 	-144.663	60    	57.3773	0.782221	7  	0.812871	0.598536   	60    	0.0531737
7  	60    	-68.3208	7  	-2.43443	-216.513	60    	34.2357	0.773805	7  	0.814733	0.541891  	60    	0.0429712
7  	60    	-41.666 	7  	-20.1924	-140.187	60    	32.8178	0.797354	7  	0.838071	0.67524  	60    	0.0199274
7  	60    	-97.584 	7  	-21.6248	-172.603	60    	20.9318	0.798894	7  	0.818706	0.647436 	60    	0.0384397
8  	60    	-40.9621	8  	64.6868 	-144.663	60    	51.6799	0.778251	8  	0.812871	0.564133   	60    	0.0594311
7  	60    	-58.7426	7  	8.49354 	-212.56 	60    	53.2706	0.783126	7  	0.819785	0.548028 	60    	0.0550168
8  	60    	-54.7649	8  	-2.43443	-236.738	60    	31.7604	0.791117	8  	0.814733	0.552597  	60    	0.0364414
8  	60    	-42.7347	8  	-13.2158	-140.187	60    	34.0805	0.802035	8  	0.89292 	0.761936 	60    	0.0202266
8  	60    	-103.819	8  	-58.9199	-400.713	60    	37.0335	0.801809	8  	0.818706	0.402608 	60    	0.0560638
9  	60    	-27.3013	9  	-1.62967	-125.803	60    	37.4502	0.801695	9  	0.812871	0.654468   	60    	0.0197449
8  	60    	-31.5109	8  	8.49354 	-143.737	60    	41.6191	0.800634	8  	0.819785	0.687754 	60    	0.0302382
9  	60    	-45.3535	9  	-13.2158	-140.187	60    	38.0168	0.804439	9  	0.89292 	0.74674  	60    	0.0315724
9  	60    	-48.0267	9  	-2.43443	-91.0657	60    	12.9838	0.799417	9  	0.814733	0.755072  	60    	0.0134907
9  	60    	-99.5304	9  	-58.9199	-118.281	60    	8.77515	0.813848	9  	0.818706	0.763086 	60    	0.0140319
10 	60    	-30.665 	10 	26.6899 	-186.79 	60    	38.8103	0.790061	10 	0.812871	0.527806   	60    	0.0502815
9  	60    	-21.0024	9  	8.49354 	-111.381	60    	27.3998	0.81201 	9  	0.819785	0.764674 	60    	0.0123017
10 	60    	-50.4728	10 	-13.2158	-167.064	60    	41.9606	0.805859	10 	0.89292 	0.685889 	60    	0.0425399
10 	60    	-53.1939	10 	-4.8856 	-144.605	60    	22.0367	0.798834	10 	0.826172	0.73551   	60    	0.0210622
10 	60    	-99.8784	10 	-68.1111	-109.162	60    	5.50081	0.813354	10 	0.818706	0.76026  	60    	0.0160824
11 	60    	-37.5652	11 	-1.62967	-134.118	60    	32.4065	0.795368	11 	0.812871	0.602116   	60    	0.0413267
11 	60    	-50.1058	11 	27.1444 	-140.187	60    	45.1164	0.816058	11 	0.89292 	0.673413 	60    	0.0446223
11 	60    	-54.2384	11 	-11.0289	-180.492	60    	21.1311	0.799643	11 	0.826172	0.613183  	60    	0.0295462
10 	60    	-19.7007	10 	8.49354 	-111.381	60    	18.7696	0.814801	10 	0.819785	0.76396  	60    	0.011141
12 	60    	-39.2711	12 	2.38312 	-126.415	60    	27.2621	0.798341	12 	0.812871	0.658195   	60    	0.0306637
11 	60    	-100.196	11 	-71.1295	-109.162	60    	3.81112	0.816287	11 	0.818706	0.798039 	60    	0.00631105

In [38]:
from pathlib import Path
import json
import pandas as pd
import numpy as np
def load_direct_data(en, cont, alg, name):
    path = f"./Data/decay_search/{en}/{cont}/{alg}/{name}"
    json_files = list(Path(path).glob("*.json"))
    print(f"Found {len(json_files)} files!")
    with open(json_files[0], "r", encoding="utf-8") as f:
        data = json.load(f)
    return data

def extract_fitness_values(file_content):
    df  = pd.json_normalize(file_content, sep="/")
    df = df.melt(var_name="path", value_name="population")
    df = df[df["path"].str.contains("fitness/")]
    df[["type", "decay","ng", "seed"]] = (df["path"].str.split("/", expand=True))
    df = df.drop(columns=["path","type"])
    df["ng"] = df["ng"].astype(int)
    df["max_fit"] = df["population"].apply(lambda x: np.max(list(map(lambda y: y[0], x))))
    df["avg_fit"] = df["population"].apply(lambda x: np.mean(list(map(lambda y: y[0], x))))
    df["median_fit"] = df["population"].apply(lambda x: np.median(list(map(lambda y: y[0], x))))
    df["min_fit"] = df["population"].apply(lambda x: np.min(list(map(lambda y: y[0], x))))
    df["std_fit"] = df["population"].apply(lambda x: np.std(list(map(lambda y: y[0], x))))
    return df
def save_final_hyperparameters(en, cont, alg, hyper_paramters):
    
    with open("relevant_finals.json", "r+", encoding="utf-8") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError:
            data = {}

        f.seek(0)       
        if cont not in data:
            data[cont] = {}
        if en not in data[cont]:
            data[cont][en] = {}
        data[cont][en][alg] = hyper_paramters
        json.dump(data, f)
        f.truncate()

In [39]:
en = "lunarlander"
cont = "add_novelty"
alg = "lambda"
file_content = load_direct_data(en, cont, alg, "")
df = extract_fitness_values(file_content)

df

Found 1 files!

,population,decay,ng,seed,max_fit,avg_fit,median_fit,min_fit,std_fit
3,"[[[-107.35161482644148], [0.40035834312438967,...",1.0,50,103,-107.351615,-107.351615,-107.351615,-107.351615,2.842171e-14
4,"[[[-79.25048589069709], [0.018930283188819886,...",1.0,50,108,-79.250486,-79.250486,-79.250486,-79.250486,2.842171e-14
5,"[[[-95.64327179150544], [0.1386697769165039, -...",1.0,50,102,-95.643272,-95.643272,-95.643272,-95.643272,2.842171e-14
6,"[[[-328.4736325811808], [-0.24376974105834961,...",1.0,50,104,-328.473633,-328.473633,-328.473633,-328.473633,1.136868e-13
7,"[[[-171.51388775824657], [-0.10178447961807251...",1.0,50,107,-171.513888,-171.513888,-171.513888,-171.513888,0.000000e+00
8,"[[[-191.64825796563696], [0.3218778133392334, ...",1.0,50,112,-121.630796,-330.185053,-352.991336,-352.991336,5.208695e+01
9,"[[[-301.45674998667675], [0.08144283294677734,...",1.0,50,109,-301.456750,-301.456750,-301.456750,-301.456750,1.705303e-13
10,"[[[-128.25811319259498], [0.2876248836517334, ...",1.0,50,111,-128.258113,-128.258113,-128.258113,-128.258113,5.684342e-14
11,"[[[-314.89217576047486], [-0.38494441509246824...",1.0,50,101,-314.892176,-314.892176,-314.892176,-314.892176,1.705303e-13
12,"[[[77.39966133256887], [0.09966484308242798, -...",1.0,50,110,77.399661,77.399661,77.399661,77.399661,0.000000e+00
13,"[[[-53.83758146471], [0.2081150531768799, -1.4...",1.0,50,114,-44.531708,-52.242289,-53.837581,-53.837581,3.507226e+00
14,"[[[-75.52974105920107], [-0.07534732818603515,...",1.0,50,105,-75.529741,-75.529741,-75.529741,-75.529741,0.000000e+00
15,"[[[-153.9583700108232], [0.31634230613708497, ...",1.0,50,106,-153.958370,-173.876502,-153.958370,-246.909652,3.814032e+01
16,"[[[-142.6334018284104], [0.15762240886688234, ...",1.0,50,113,-142.633402,-142.633402,-142.633402,-142.633402,0.000000e+00
17,"[[[-328.4736325811808], [-0.24376974105834961,...",3.0,50,104,-328.473633,-328.473633,-328.473633,-328.473633,1.136868e-13
18,"[[[-171.51388775824657], [-0.10178447961807251...",3.0,50,107,-171.513888,-171.513888,-171.513888,-171.513888,0.000000e+00
19,"[[[-107.35161482644148], [0.40035834312438967,...",3.0,50,103,-107.351615,-107.351615,-107.351615,-107.351615,2.842171e-14
20,"[[[-314.89217576047486], [-0.38494441509246824...",3.0,50,101,-314.892176,-314.892176,-314.892176,-314.892176,1.705303e-13
21,"[[[-301.45674998667675], [0.08144283294677734,...",3.0,50,109,-301.456750,-301.456750,-301.456750,-301.456750,1.705303e-13
22,"[[[-191.64825796563696], [0.3218778133392334, ...",3.0,50,112,-121.630796,-330.185053,-352.991336,-352.991336,5.208695e+01
23,"[[[-53.83758146471], [0.2081150531768799, -1.4...",3.0,50,114,-44.531708,-52.242289,-53.837581,-53.837581,3.507226e+00
24,"[[[-95.64327179150544], [0.1386697769165039, -...",3.0,50,102,-95.643272,-95.643272,-95.643272,-95.643272,2.842171e-14
25,"[[[-128.25811319259498], [0.2876248836517334, ...",3.0,50,111,-128.258113,-128.258113,-128.258113,-128.258113,5.684342e-14
26,"[[[77.39966133256887], [0.09966484308242798, -...",3.0,50,110,77.399661,77.399661,77.399661,77.399661,0.000000e+00
27,"[[[-142.6334018284104], [0.15762240886688234, ...",3.0,50,113,-142.633402,-142.633402,-142.633402,-142.633402,0.000000e+00
28,"[[[-79.25048589069709], [0.018930283188819886,...",3.0,50,108,-79.250486,-79.250486,-79.250486,-79.250486,2.842171e-14
29,"[[[-75.52974105920107], [-0.07534732818603515,...",3.0,50,105,-75.529741,-75.529741,-75.529741,-75.529741,0.000000e+00
30,"[[[-153.9583700108232], [0.31634230613708497, ...",3.0,50,106,-153.958370,-173.876502,-153.958370,-246.909652,3.814032e+01
31,"[[[-328.4736325811808], [-0.24376974105834961,...",2.0,50,104,-328.473633,-328.473633,-328.473633,-328.473633,1.136868e-13
32,"[[[77.39966133256887], [0.09966484308242798, -...",2.0,50,110,77.399661,77.399661,77.399661,77.399661,0.000000e+00
33,"[[[-75.52974105920107], [-0.07534732818603515,...",2.0,50,105,-75.529741,-75.529741,-75.529741,-75.529741,0.000000e+00
34,"[[[-301.45674998667675], [0.08144283294677734,...",2.0,50,109,-301.456750,-301.456750,-301.456750,-301.456750,1.705303e-13
35,"[[[-79.25048589069709], [0.018930283188819886,...",2.0,50,108,-79.250486,-79.250486,-79.250486,-79.250486,2.842171e-14
36,"[[[-107.35161482644148], [0.40035834312438967,...",2.0,50,103,-107.351615,-107.351615,-107.351615,-107.351615,2.842171e-14
37,"[[[-128.25811319259498], [0.2876248836517334, ...",2.0,50,111,-128.258113,-128.258113,-128.258113,-128.258113,5.684342e-14
38,"[[[-171.51388775824657], [-0.10178447961807251...",2.0,50,107,-171.513888,-171.513888,-171.513888,-171.513888,0.000000e+00
39,"[[[-95.64327179150544], [0.1386697769165039, -...",2.0,50,102,-95.643272,-95.643272,-95.643272,-95.643272,2.842171e-14
40,"[[[-53.83758146471], [0.2081150531768799, -1.4...",2.0,50,114,-44.531708,-52.242289,-53.837581,-53.837581,3.507226e+00
41,"[[[-314.89217576047486], [-0.38494441509246824...",2.0,50,101,-314.892176,-314.892176,-314.892176,-314.892176,1.705303e-13
42,"[[[-153.9583700108232], [0.31634230613708497, ...",2.0,50,106,-153.958370,-173.876502,-153.958370,-246.909652,3.814032e+01
43,"[[[-142.6334018284104], [0.15762240886688234, ...",2.0,50,113,-142.633402,-142.633402,-142.633402,-142.633402,0.000000e+00
44,"[[[-191.64825796563696], [0.3218778133392334, ...",2.0,50,112,-121.630796,-330.185053,-352.991336,-352.991336,5.208695e+01
45,"[[[-79.25048589069709], [0.018930283188819886,...",0.5,50,108,-79.250486,-79.250486,-79.250486,-79.250486,2.842171e-14
46,"[[[-153.9583700108232], [0.31634230613708497, ...",0.5,50,106,-153.958370,-173.876502,-153.958370,-246.909652,3.814032e+01
47,"[[[-53.83758146471], [0.2081150531768799, -1.4...",0.5,50,114,-44.531708,-52.242289,-53.837581,-53.837581,3.507226e+00
48,"[[[-142.6334018284104], [0.15762240886688234, ...",0.5,50,113,-142.633402,-142.633402,-142.633402,-142.633402,0.000000e+00
49,"[[[-107.35161482644148], [0.40035834312438967,...",0.5,50,103,-107.351615,-107.351615,-107.351615,-107.351615,2.842171e-14
50,"[[[-75.52974105920107], [-0.07534732818603515,...",0.5,50,105,-75.529741,-75.529741,-75.529741,-75.529741,0.000000e+00
51,"[[[-191.64825796563696], [0.3218778133392334, ...",0.5,50,112,-121.630796,-330.185053,-352.991336,-352.991336,5.208695e+01
52,"[[[-328.4736325811808], [-0.24376974105834961,...",0.5,50,104,-328.473633,-328.473633,-328.473633,-328.473633,1.136868e-13
53,"[[[77.39966133256887], [0.09966484308242798, -...",0.5,50,110,77.399661,77.399661,77.399661,77.399661,0.000000e+00
54,"[[[-128.25811319259498], [0.2876248836517334, ...",0.5,50,111,-128.258113,-128.258113,-128.258113,-128.258113,5.684342e-14
55,"[[[-95.64327179150544], [0.1386697769165039, -...",0.5,50,102,-95.643272,-95.643272,-95.643272,-95.643272,2.842171e-14
56,"[[[-301.45674998667675], [0.08144283294677734,...",0.5,50,109,-301.456750,-301.456750,-301.456750,-301.456750,1.705303e-13
57,"[[[-314.89217576047486], [-0.38494441509246824...",0.5,50,101,-314.892176,-314.892176,-314.892176,-314.892176,1.705303e-13
58,"[[[-171.51388775824657], [-0.10178447961807251...",0.5,50,107,-171.513888,-171.513888,-171.513888,-171.513888,0.000000e+00

In [49]:
import seaborn as sns
df = df.sort_values("decay")
ploted_df = df[["decay", "seed", "max_fit", "median_fit", "avg_fit"]]
ploted_df = ploted_df.groupby("decay").max()
ploted_df
# if "seed" in ploted_df.columns:
#     ploted_df = ploted_df.drop(columns="seed")
# ploted_df = ploted_df.melt(
#         id_vars="decay", 
#         var_name="type", 
#         value_name="value"
#     )
# sns.lineplot(data=ploted_df, x="decay", y="value", hue="type")

      seed    max_fit  median_fit    avg_fit
decay
0.5    114  77.399661   77.399661  77.399661
1.0    114  77.399661   77.399661  77.399661
2.0    114  77.399661   77.399661  77.399661
3.0    114  77.399661   77.399661  77.399661